---
image:
  pullPolicy: Always

serviceAccount:
  create: true

service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    # Associate a GCP FrontendConfig with the Ingress
    # networking.gke.io/v1beta1.FrontendConfig: "<name>"

