{{- if .Values.secret.external.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  secretStoreRef:
{{- .Values.storeRef | toYaml | nindent 4 }}
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Merge
  template:
    type: Opaque
  dataFrom:
    - key: {{ .Values.secrets.external.path }}
{{- end }}
