{{- if .Values.secret.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  secretStoreRef:
    {{- .Values.secret.external.storeRef | toYaml | nindent 4 }}
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: {{ .Values.secret.external.path }}
        decryptionStrategy: Auto
{{- end }}
