inherit_from: .rubocop_todo.yml
AllCops:
    NewCops: enable

require:
 - rubocop-factory_bot
 - rubocop-rails
 - rubocop-rake
 - rubocop-rspec

Style/IfUnlessModifier:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false
