inherit_from: .rubocop_todo.yml
AllCops:
    NewCops: enable

require:
 - rubocop-factory_bot
 - rubocop-rails
 - rubocop-rake
 - rubocop-rspec
 - rubocop-rspec_rails

Style/IfUnlessModifier:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false
