inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake

Style/IfUnlessModifier:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  Max: 100

Metrics/BlockLength:
  Enabled: true
  Max: 100

Metrics/ModuleLength:
  Enabled: true
  Max: 100
  
Metrics/MethodLength:
  Enabled: true
  Max: 50

Metrics/AbcSize:
  Enabled: false

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit
  EnforcedHashRocketStyle: table

Style/NumericPredicate:
  Enabled: false