= Setting Up the App in Development
:doctype: book
:source-highlighter: rouge
:rouge-style: base16.monokai
:toclevels: 5
:toc:
:sectnums: 9
:icons: font
:license: MIT

== Getting Started

If you want to contribute to the TicketBooth codebase, there's a few things
you need to do in order to get started.

=== Pre-requisites

* Run a Mac or Linux operating system.

* XCode installed (or XCode Dev Tools)

* You probably are going to use https://brew.sh/[Homebrew] for installing package:

[source,bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
----

== Easy Route

If you are on OS-X, you can use the provided `bin/dev-tooling` script to install the necessary tools and dependencies. The script is generally kept up to date.

It has the following usage:

[source,bash]
----
❯ dev-tooling -h
USAGE:
  ./bin/dev-tooling [--help]  
                    [--vim] [--psqlrc] [--upgrade-brew]
                    [--skip-node] [--skip-db] [--skip-brew]

FLAGS:
  --vim    | -v  Install custom VIM configuration (and backup existing)
  --psqlrc | -p  Install ~/.psqlrc file configuration (recommended)
  --help   | -h  Show this help message
  --upgrade-brew Upgrade Brew packages. Otherwise uses locked versions.
  --skip-db      Do not setup the database or run migrations
  --skip-node    Do not install NodeJS or Yarn.
----

If you've never used VIM, or you have your personal configuration that's deliberate and intentional, do not use the `--vim` flag. If, however, you are familiar with VIM, but haven't invested into a proper configuration, add `--vim` to the command line to install the custom configuration that got syntax highlighting, auto-complete, and other useful features.

If you've never used the `psql` command and have no intention to, or vice versa, if you have your personal configuration that's deliberate and intentional, do not use the `--psqlrc` flag. If, however, you are familiar with `psql`, but haven't invested into a proper configuration, add `--psqlrc` to the command line to install the custom initialization file that will allow you to load SQL macros with `:m` or `:macros` command, and provides a nice looking prompt that shows you the database you are connected to and the version of PostgreSQL you are using, etc.

The `--upgrade-brew` flag is used to upgrade the Brew packages to the latest versions. If you don't use this flag, the script will use the locked versions of the packages, which might be outdated. But if you do use this flag, you will likely end up with an updated `Brewfile.lock.json` file, which you probably should commit to the repository together (or separately) with your changes.

Running this script should get you:

* Many required, some optional but very useful tools and dependencies installed.
* VIM configuration installed (if you use it).
* `psql` initialization file installed (if you use it).
* Ruby, with version specified in the `.ruby-version` file installed.
* All the necessary Gems installed, as well as some external gems such as `ruby-lsp` necessary for IDE integration.
* NodeJS (LTS) installed using Volta, Yarn installed, and the project's dependencies installed.
* The database created, migrated, and seeded. 
* The script will also set up `direnv` to automatically load the environment variables from the `.envrc` file.

=== Starting the Dev Server

There are several largely equivalent ways to start the server:

* `make dev` - this will run the server using `foreman -f Procfile.dev`.
* `foreman -f Procfile.dev` - this will run the server using `foreman -f Procfile.dev` explicitly.
* `bin/dev-start` - this will run the server using `foreman -f Procfile.dev` as well.

All of the above commands will start the web server on port 8080, and the browser will open the URL automatically.

[IMPORTANT] 
.Why do we need to use foreman and the Procfile.dev?
==== 
Many "vanilla" Rails applications are started with the command `rails s`, which starts the Rails server.

However, we are using advanced CSS/JS pipeline that requires additional processes to be running in order to serve CSS and JS assets properly, and recompile them on the fly as they change. This is the primary reason for using `Procfile.dev` and the commands that use it listed above.
====

== How to Deploy to Production (2026)

To deploy to production site — https://tickets.fnf.events — the deployer's IP address must be white-listed with EC2. Contact Konstantin Gredeskoul to get white-listed.

The deploy is performed via Capistrano:

[source,bash]
----
git checkout main
git pull
bundle install -j 12
# Run this if you haven't yet
bin/dev-tooling # installs local dev dependencies
bin/deploy      # actually performs the deployment using Capistrano
----

==== Running Tests and Linters

To verify that your local environment is working, run the following:

[source,bash]
----
bundle exec rspec
bundle exec rubocop
bin/shchk
----


[source,bash]
----
make ci
----


== Manual Setup

If you are a masochist, you can follow the steps below to set up the environment manually. Good luck with that.

NOTE: The steps below may be outdated. The `bin/dev-tooling` script is the **up-to-date** way to set up the environment.

=== Ruby

* You are probably going to need `rbenv` and `ruby-build`:

[source,bash]
----
# ensure that failed commands do not terminate the shell
set +e

# install rbenv
brew update && brew install rbenv ruby-build direnv

# now let's make sure we enable rbenv in our shell init file at the very end:
init="${HOME}/.zshrc"
grep -q "rbenv init" "${init}"  || echo 'eval "$(rbenv init - zsh)"' >> "${init}"
grep -q "direnv hook" "${init}" || echo 'eval "$(direnv hook zsh)"' >> "${init}"

# load it up to activate rbenv in this session
source ~/.zshrc
----

=== Checkout the Source

* Clone this repository:

[source,bash]
----
cd ~/ && mkdir -p workspace/fnf/ && cd workspace/fnf
git clone git@github.com:fnf-org/ticket-booth.git && cd ticket-booth

# enable auto-loading of the .envrc file
direnv allow .

# Install the appropriate version of Ruby
rbenv install -s $(cat .ruby-version)

# Install bundler, and install the dependend gems
gem install bundler --version 2.3.11 -N
bundle install -j 12
----

=== Configuration

* Copy the `config/database.yml.example` file to `config/database.yml`, and
edit the `username` and `password` fields to match the user/password you
chose in the previous step (you can use the defaults if you want).

* Copy the `config/stripe.yml.example` file to `config/stripe.yml`. If you
have your own Stripe account that you want to test with, use the secret
key and public key from that account instead (but the defaults will work
out of the box if you don't want to use your own Stripe account).

* Create the databases using the information you defined in
`config/database.yml` by running `rake db:create`

* Fill the database with tables by running the database migrations:
`rake db:migrate db:test:prepare`
** NOTE - the `db:test:prepare` is necessary only if you want to run the tests

You should now be all set. Try spinning up a local development server by
running:

[source,bash]
bundle exec rails server

OR
[source,bash]
bundle exec puma -C config/puma.rb

This should run an all-in-one server that you can access from your browser
at http://localhost:3000[http://localhost:3000]. It will also automatically load any changes
you make to code in the repo's `app` directory. Changes anywhere else will
require you to restart the server.

If you want to work within a Ruby console, `rails console` is incredibly
useful for playing around in the Rails environment.

== Contributing

=== Write helpful commit messages

When making changes to the code, ensure your commit messages are descriptive.
A good summary of git commit messages can be found
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[here],
but you can look at the repository history for some examples using `git log`.

=== Write tests

Automated tests are your friend. See the `spec` directory for examples.
You can run the automated tests by running `bundle exec rspec spec`
(where `spec` is the directory of specs, or individual list of specs, that you
want to run) in the repository.

Check the `coverage` folder, eg.

[source,bash]
bundle exec rspec && open coverage/index.html

To run both the specs and rubocop:
[source,bash]
rake

== Deploying

If your SSH public key has been added to the production server's list of
authorized keys, you can deploy the latest version of the code to the
production site using `cap deploy`. Before you do this, remember to push
your local changes to the `origin` repository with `git push origin master`,
as the deploy process can only deploy code from that canonical source.

If you don't have permission to deploy, you can submit a pull request to
the repository and someone will review your code and merge it if it's good
to go.

See https://help.github.com/articles/using-pull-requests[Using Pull Requests]
for more information on this process if you are not familiar.

