= Ticket Booth
:doctype: book
:source-highlighter: rouge
:rouge-style: base16.monokai
:toc:
:icons: font
:license: MIT

[cols=">h", width="30%"]
|===
| Test & Lint Status | Build & Packaging Status
|
https://github.com/fnf-org/TicketBooth/actions/workflows/rspec.yml[image:https://github.com/fnf-org/TicketBooth/actions/workflows/rspec.yml/badge.svg[TicketBooth CI: RSpec]]

https://github.com/fnf-org/TicketBooth/actions/workflows/lint.yml[image:https://github.com/fnf-org/TicketBooth/actions/workflows/lint.yml/badge.svg[TicketBooth CI: RuboCop]]

https://github.com/fnf-org/TicketBooth/actions/workflows/audit.yml[image:https://github.com/fnf-org/TicketBooth/actions/workflows/audit.yml/badge.svg[Bundle Audit]]

|

|===

====
NOTE: Please see the https://github.com/fnf-org/TicketBooth/blob/main/README.pdf[README.pdf] for the PDF version of this README.

---

NOTE: Please see the xref:#acknowledgements[Acknowledgements] at the end of this page.
====

https://liberapay.com/kigster/donate[image:https://liberapay.com/assets/widgets/donate.svg[Donate
using Liberapay]]

== Welcome to the *Ticket Booth*!

The goal of the app is to make ticket and volunteer management for community events easier and automated.

=== Information For Developers

We have a dedicated document for the folks that might be working on this app, fixing bugs or building new features. We moved all of this info into  xref:DEVELOPERS.pdf[developer setup] document, which helps you get the application running locally.

=== Adding Site Admin

When the database is completely blank, the first step is to create the initial account. Lets say you registered as 'kig@fnf.org':

The second step is to make that person a site admin:

[source,bash]
----
RAILS_ENV=production
bin/site-admin add kig@fnf.org

# Or, to remove site admin from a given user:
bin/site-admin remove kig@fnf.org
----

=== Generating Music Submissions List

The repo contains a convenient script for generating HTML to embed into the Wordpress site, using a CSV generated out of Google Spreadsheet collected using Google Forms.

The CSV must contain three columns and a header row:

 * DJ Name
 * Full Name
 * Set URL

To generate the HTML (we'll use the CSV file checked into the fixtures):

[source,bash]
----
# eg, using the fixture file:
$ bin/music-submission-links spec/fixtures/chill_sets.csv > chill_set.html

# or, to include the simple CSS into the header:
$ bin/music-submission-links spec/fixtures/chill_sets.csv --simple-css > chill_set.html
open chill_set.html
----

[WARNING]
====
 If you add `--simple-css` to the arguments, the generated HTML will include `<head>` element with the https://simplecss.org/[Simple CSS Stylesheet]. Do not use this flag if you plan to paste the output into the WordPress text box. Use this flag if you simply want to verify the resulting HTML in a browser by running `open chill_set.html`.
====

To verify that the script is working and generating correct HTML, you might want to install a handy tool called `bat`, eg using Homebrew on Mac OS-X:

[source,bash]
----
$ brew install bat
$ bin/music-submission-links spec/fixtures/chill_sets.csv | bat
----

===== Adding Submissions to WordPress

Now you can open WordPress, create a two-column layout on the submissions page and paste the contents into one of the two columns, typically:

 1. Night time / Peak Hour
 2. Chill / Daytime

First, let's copy the resulting HTML into clipboard:

[source,bash]
----
$ bin/music-submission-links chill_sets.csv | pbcopy
----

Now we can paste it into WordPress directly.

== API Documentation

Yard-generated documentation is available via running:

[source,bash]
----
$ bundle exec rake doc
# this will automatically open the index.html
----

== Acknowledgements

This app is formerly known as **Helping Culture**, which in turn was originally conceived and inspired by Tracy Page.

This project was originally written by https://github.com/sds[Shane de Silva].

It is currently maintained by the https://github.com/fnf-org[FnF] org, and within it specifically

 * https://github.com/kigster[Konstantin Gredeskoul] for any Rails, Ruby, or application issues,
 * https://github.com/ev1lm0nk3y[Ryan Shatford] and https://github.com/mike-matera[Mike Matera] for any issues related to deployment to the Google Public Cloud.
 * https://github.com/beingmattlevy[Matt Levy] for development, coordination and project management.

Please use labels to tag any reported issues.

