development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: postgres
  database: ticketing_app_development

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: postgres
  database: ticketing_app_test

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: postgres
  database: ticketing_app_production
  pool: 15
