# config/payment.yml
production: &production
  min_threads: <%= Integer(ENV.fetch('PUMA_THREADS', 3)) %>
  max_threads: <%= Integer(ENV.fetch('PUMA_THREADS', 3)) %>
  workers: <%= Integer(ENV.fetch('PUMA_WORKERS',  [Etc.nprocessors - 1, 4].min)) %>
  port: <%= Integer(ENV.fetch('PUMA_PORT', 3001)) %>
  host: "<%= ENV.fetch('TICKETS_HOST', 'https://tickets.fnf.events') %>"

staging:
  <<: *production

development: &development
  min_threads: 1
  max_threads: 1
  workers: 1
  port: 8080
  host: http://localhost:8080

test:
  <<: *development
