# Defines the secret key base used for signing cookies and other things. If you
# change this, all current cookies will become invalidated. This version is
# provided in the repo for convenience, but the one in production must never be
# shared publicly or stored in source control, as that is a security liability.
secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
