name: BASH ShellCheck
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        check_together: 'yes'
        scandir: './bin'
        ignore_names: init.sh
permissions:
  checks: read
  contents: read
  statuses: read
