name: BASH ShellCheck
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      run: bin/shchk
permissions:
  checks: read
  contents: read
  statuses: read
