# .github/workflows/main.yaml
name: "TicketBooth CI: Lint"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -yqq
      - run: sudo apt-get install -yqq libpq-dev

      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: false

      - name: RuboCop
        run: bundle exec rubocop --format progress
