# .github/workflows/main.yaml
name: "TicketBooth CI: rspec"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    name: CI
    runs-on: ubuntu-latest

    # If you need DB like MySQL then define service below.
    # Example for PostgreSQL and Redis can be found here:
    # https://github.com/actions/example-services/tree/master/.github/workflows
    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: niden/actions-memcached@v7

      - run: sudo apt-get update -yqq
      - run: sudo apt-get install -yqq netcat libpq-dev

      - name: "Verify Memcached is running"
        run: echo -e "stats\nquit" | nc localhost 11211  | grep -e "accepting_conns 1" -q

      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true

      - name: "Create and migrate the DB"
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:test:prepare

      - name: "Run Rspec"
        run: bundle exec rspec --format documentation

      - name: "Run Rubocop"
        run: bundle exec rubocop


  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true

      - name: RuboCop
        run: bin/rubocop --parallel
