name: "TicketBooth CI: Ruby"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ruby:3.2

    # Service containers to run with `container-job`
    services:
      postgres:
        # Docker Hub image
        image: postgres:16
        # Provide the password for postgres
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: "trust"

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10sa
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: niden/actions-memcached@v7
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2.3' # Not needed with a .ruby-version file
          bundler-cache: true

      - run: bundle install -j 12
      - run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:test:prepare
      - run: bundle exec rspec --format documentation
      - run: bundle exec rubocop

